md = fs.makeDir
ts = textutils.slowPrint
sr = shell.run
re = os.reboot
ts("Installer for CPOS Threshold")
ts("Version 0.1 Public Preview")
ts("============================")
ts("Setting up folders")
md("Computer")
md("Computer/System")
md("Computer/Home")
md("Computer/Home/Desktop")
md("Computer/Home/Documents")
md("Computer/System/Library")
md("Computer/System/Library/Computer")
md("Computer/System/Library/FirstRun.app")
md("Computer/System/Library/Frameworks")
md("Computer/System/Library/Interface")
md("Computer/System/Library/Frameworks/Interface")
md("Computer/System/Library/Frameworks/Services")
md("Computer/System/Library/Documentation")
md("Computer/System/Applications")
md("Computer/System/Applications/Finder.app")
md("Computer/System/Applications/TextEdit.app")
md("Computer/System/Applications/System Preferences.app")
sleep(5)
ts("ing and installing Apps")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/Finder.app/Finder", "Computer/System/Applications/Finder.app/Finder")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/Finder.app/icon", "Computer/System/Applications/Finder.app/icon")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/Finder.app/icon_l", "Computer/System/Applications/Finder.app/icon_l")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/Finder.app/icon_s", "Computer/System/Applications/Finder.app/icon_s")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/System%20Preferences.app/System%20Preferences", "Computer/System/Applications/System Preferences.app/System Preferences")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/System%20Preferences.app/icon", "Computer/System/Applications/System Preferences/icon")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/System%20Preferences.app/icon_l", "Computer/System/Applications/System Preferences/icon_l")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/TextEdit.app/TextEdit", "Computer/System/Applications/TextEdit.app/TextEdit")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/TextEdit.app/icon", "Computer/System/Applications/TextEdit.app/icon")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Applications/TextEdit.app/icon_l", "Computer/System/Applications/TextEdit.app/icon_l")
ts("Finshed ing and Installing apps")
ts("ing and installing system files")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/clean", "Computer/System/clean")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/OSDrawingOld", "OSDrawingOld")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/Startup", "Computer/startup")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/FirstRun.app/FirstRun", "System/Library/FirstRun.app/FirstRun")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Interface/CPOSLogo", "Computer/System/Library/Interface/CPOSLogo")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Interface/icon_l", "Computer/System/Library/Interface/icon_l")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Interface/minimise", "Computer/System/Library/Interface/minimise")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Computer/CraftOS", "Computer/System/Library/Computer/CraftOS")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Computer/Restart", "Computer/System/Library/Computer/Restart")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Computer/Shutdown", "Computer/System/Library/Computer/Shutdown")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Computer/Sleep2", "Computer/System/Library/Computer/Sleep2")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Computer/SwitchScreen", "Computer/System/Library/Computer/SwitchScreen")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Services/OSFileSystem", "Computer/System/Library/Frameworks/Services/OSFileSystem")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Services/OSInterfaceEntities", "Computer/System/Library/Frameworks/Services/OSInterfaceEntities")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Services/OSKeyboardShortcuts", "Computer/System/Library/Frameworks/Services/OSKeyboardShortcuts")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Services/OSServices", "Computer/System/Library/Frameworks/Services/OSServices")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Services/OSTableIO", "Computer/System/Library/Frameworks/Services/OSTableIO")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSAboutWindow", "Computer/System/Library/Frameworks/Interface/OSAboutWindow")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSApplication", "Computer/System/Library/Frameworks/Interface/OSApplication")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSBox", "Computer/System/Library/Frameworks/Interface/OSBox")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSButton", "Computer/System/Library/Frameworks/Interface/OSButton")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSCheckBox", "Computer/System/Library/Frameworks/Interface/OSCheckBox")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSClockButton", "Computer/System/Library/Frameworks/Interface/OSClockButton")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSContainer", "Computer/System/Library/Frameworks/Interface/OSContainer")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSControl", "Computer/System/Library/Frameworks/Interface/OSControl")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSDesktop", "Computer/System/Library/Frameworks/Interface/OSDesktop")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSDock", "Computer/System/Library/Frameworks/Interface/OSDock")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSDockItem", "Computer/System/Library/Frameworks/Interface/OSDockItem")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSDrawing", "Computer/System/Library/Frameworks/Interface/OSDrawing")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSEntity", "Computer/System/Library/Frameworks/Interface/OSEntity")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSHSplitter", "Computer/System/Library/Frameworks/Interface/OSHSplitter")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSImageView", "Computer/System/Library/Frameworks/Interface/OSImageView")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSInterfaceApplications", "Computer/System/Library/Frameworks/Interface/OSInterfaceApplications")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSInterfaceEntities", "Computer/System/Library/Frameworks/Interface/OSInterfaceEntities")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSLabel", "Computer/System/Library/Frameworks/Interface/OSLabel")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSListItem", "Computer/System/Library/Frameworks/Interface/OSListItem")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSListView", "Computer/System/Library/Frameworks/Interface/OSListView")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSMenu", "Computer/System/Library/Frameworks/Interface")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSMenuBar", "Computer/System/Library/Frameworks/Interface/OSMenuBar")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSMenuItem", "Computer/System/Library/Frameworks/Interface/OSMenuItem")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSMenuSplitter", "Computer/System/Library/Frameworks/Interface/OSMenuSplitter")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSObject", "Computer/System/Library/Frameworks/Interface/OSObject")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSProgressBar", "Computer/System/Library/Frameworks/Interface/OSProgressBar")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSTextField", "Computer/System/Library/Frameworks/Interface/OSTextField")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSTextView", "Computer/System/Library/Frameworks/Interface/OSTextView")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSVSplitter", "Computer/System/Library/Frameworks/Interface/OSVSplitter")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/System/Library/Frameworks/Interface/OSWindow", "Computer/System/Library/Frameworks/Interface/OSWindow")
ts("Done downloading and installing system files")
ts("Doing misc s and installs")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/Home/Desktop/Notes.txt", "Computer/Home/Desktop/Notes.txt")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/Home/Documents/Welcome!.txt", "Computer/Home/Documents/Welcome!.txt")
sr("package", "https://raw.githubusercontent.com/Cloudpaw/CPOS/master/Computer/Settings", "Computer/Settings")
ts("CPOS is now done installing!")
ts("This computer will reboot ....................... now")
re()